ALTER TABLE quotations
ADD COLUMN IF NOT EXISTS recipient_name VARCHAR(160);

ALTER TABLE quotations
ADD COLUMN IF NOT EXISTS recipient_email VARCHAR(160);

ALTER TABLE quotations
ADD COLUMN IF NOT EXISTS shared_via_email BOOLEAN NOT NULL DEFAULT FALSE;
